build:
  image: teaci/msys32
  shell: mingw32
  pull: true
  commands:
    - pacman -Syu --needed --noprogressbar --noconfirm mingw-w64-i686-toolchain mingw-w64-i686-qt5
    - qmake m_pi
    - mingw32-make
